### PR TITLE
preparations for the junit5 module

### PR DESCRIPTION
**Pull request by svenruppert**
- separation of the junit4 and junit5 code into different modules.
- core module to share code between different TDD frameworks

### CODE REVIEW

**Comment by svenruppert** [comment]
hhmm com.fnproject.fn:fn-spring-cloud-function:jar:1.0.60 is missing..

**Comment by zootalures** [comment]
Hmm that doesn’t look right, that should be a sub-module of this project @mjg123 can you take a look?

**Comment by mjg123** [comment]
Yes - although I'm travelling rn so it's not going to be straight away.

**Comment by svenruppert** [comment]
merged master into PR, but the build ends on circleci again at the module fn-spring-cloud-function.
I checked the diff between master and PR, but this part is 100% the same. Changes are only after this point, during compile/install.  Please, have a look at this. 

 Cheers Sven

---- SNIP -- LOG ----
1214/1214 KB   1212/1212 KB   
                              
Downloaded: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.8.10/jackson-databind-2.8.10.jar (1214 KB at 7492.7 KB/sec)
                              
Downloaded: https://repo.maven.apache.org/maven2/io/projectreactor/reactor-core/3.0.7.RELEASE/reactor-core-3.0.7.RELEASE.jar (1212 KB at 6960.5 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] fdk ................................................ SUCCESS [  6.936 s]
[INFO] api ................................................ SUCCESS [ 17.221 s]
[INFO] runtime ............................................ SUCCESS [ 12.788 s]
[INFO] testing ............................................ SUCCESS [  0.019 s]
[INFO] fn-spring-cloud-function ........................... FAILURE [  4.098 s]
[INFO] testing-core ....................................... SKIPPED
[INFO] testing-junit4 ..................................... SKIPPED
[INFO] testing-junit5 ..................................... SKIPPED
[INFO] string-reverse ..................................... SKIPPED
[INFO] regex-query ........................................ SKIPPED
[INFO] async-thumbnails ................................... SKIPPED
[INFO] fdk-examples ....................................... SKIPPED
[INFO] integration-tests .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 41.312 s
[INFO] Finished at: 2018-06-25T03:39:25+00:00
[INFO] Final Memory: 74M/497M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project fn-spring-cloud-function: Could not resolve dependencies for project com.fnproject.fn:fn-spring-cloud-function:jar:1.0.63: Could not find artifact com.fnproject.fn:testing:jar:1.0.63 in spring-milestones (https://repo.spring.io/milestone) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :fn-spring-cloud-function
Exited with code 1

**Comment by mjg123** [comment]
Hi - I rebased this onto a branch I made updating all the dependencies - new PR is here: https://github.com/fnproject/fdk-java/pull/144

**Comment by svenruppert** [comment]
We can close this one, working on #144 and #145 ff.

**Pull request closed without merging**
