### PR TITLE
Feature/junit5

### PR DESCRIPTION
**Pull request by mjg123**
Rebase of this https://github.com/fnproject/fdk-java/pull/141
onto this https://github.com/fnproject/fdk-java/pull/143

### CODE REVIEW

**Comment by mjg123** [comment]
CI fails, but it passed locally :(

**Comment by mjg123** [comment]
All passing except for timeouts in the integration tests.

**Comment by svenruppert** [comment]
created preparations at https://github.com/fnproject/fdk-java/pull/145

**Comment by mjg123** [comment]
Closing in favour of #145

**Pull request closed without merging**
