### PR TITLE
Feature/junit5 preparations

### PR DESCRIPTION
**Pull request by svenruppert**
extracted the junit4 code into separate module
all dependencies are using this right now inside this project
module testing is empty so far, but will contain junit5 code later

this merge request is based on the need to hold the old module name **testing**
**testing-junit4** will be used for the orig testing code base
**teting-core** will be used for the generic code that could be used for junit4 and junit5 
**testing** will be the "home" for the new junit5 code base

### CODE REVIEW

**Comment by svenruppert** [comment]
for integration test-7 : https://github.com/fnproject/cli/pull/349

With this we can use junit4 as default until we are switching to jUnit5 as default.

**Comment by mjg123** [comment]
Compilation failure in the integration tests - I'll have a look.

**Comment by svenruppert** [comment]
it should be integration test 7, that is using cli

**Comment by svenruppert** [comment]
deactivated integration test 3 and 7 to break the cycle between cli and fdk

**Pull request merged**
