### PR TITLE
Set stable automatic module names

### PR DESCRIPTION
**Pull request by sormuras**
Draft PR setting `com.fnproject.fn.api` as the automatic module name for `fdk-java/api` module. I'd be happy to extend this PR to all other relevant modules.

Addresses #188

### CODE REVIEW

**Comment by sormuras** [comment]
Dear "cla_bot", I already signed the CLA. Find "Christian Stein - OpenJDK - sor" at https://www.oracle.com/technetwork/community/oca-486395.html#s

**Comment by delabassee** [comment]
@sormuras indeed, let us check how to make the bot happy

**Comment by sormuras** [comment]
@delabassee Any news here? Happy bot in sight?

**Comment by sormuras** [comment]
Now it reads [`Christian Stein - OpenJDK / Fn Project - sor`](https://www.oracle.com/technetwork/community/oca-486395.html#s) but the bot is still unhappy.

**Comment by sormuras** [comment]
Closing due to ... today, FDK-Java should ship as explicit Java modules.

**Pull request closed without merging**
